### ISSUE TITLE
New pandas 1.2.0 breaks compatibility with numpy

### ISSUE THREAD

**Issue by tquid** [alexnathanson/solar-protocol#3]
pandas 1.2.0 came out today, and it breaks compatibility with numpy:

```
Traceback (most recent call last):
  File "/home/pi/solar-protocol/charge-controller/csv_datalogger.py", line 6, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.7/dist-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat.numpy import (
  File "/usr/local/lib/python3.7/dist-packages/pandas/compat/numpy/__init__.py", line 21, in <module>
    f"this version of pandas is incompatible with numpy < {_min_numpy_ver}\n"
ImportError: this version of pandas is incompatible with numpy < 1.16.5
your numpy version is 1.16.2.
Please upgrade numpy to >= 1.16.5 to use this pandas version
```

**Comment by tquid** [comment]
I tried uninstalling pandas and reinstalling with `pandas==1.1.5` and that seems to do the trick, as a workaround.
